controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\web\Controller;
use app\models\Students;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        if (Yii::$app->request->isPost) {

            return $this->render('index', [
                'searchModel' => Yii::$app->request->post()
            ]);
        }
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password_hash = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionForgotpassword()
    {
        $model = new User();
        if ($model->load(Yii::$app->request->post()) && $model->login != '') {


            $user = User::findOne(['login' => $model->login]);

            if ($user) {
                if ($user->status == User::STATUS_ACTIVE) {

                    $newpassword = (string)rand(100001, 999999);

                    $user->password_hash = $newpassword;

                    $user->save('test');

                    //Yii::$app->session->setFlash('success', $newpassword);

                    if ($user->email != '') {
                        $strText = Yii::$app->params['settings']['textMailUserPassword'];
                        $strText = str_replace("#NAME#", $user->name, $strText);
                        $strText = str_replace("#LOGIN#", $user->login, $strText);
                        $strText = str_replace("#PASSWORD#", $newpassword, $strText);
                        $strText = str_replace("#URL_SITE#", $_SERVER['SERVER_NAME'], $strText);
                        $strText = str_replace("#adminEmail#", Yii::$app->params['adminEmail'], $strText);

                        $arResult = $strText;

                        Yii::$app->mailer->compose('reset_password', ['arResult' => $arResult])
                            ->setFrom(Yii::$app->params['sendFrom'])
                            ->setTo($user->email)
                            ->setSubject('Восстановление пароля ' . $_SERVER['SERVER_NAME'])
                            ->send();
                    }


                    Yii::$app->session->setFlash('forgotpasswordSubmitted');

                } else {
                    Yii::$app->session->setFlash('error', Yii::$app->params['settings']['errorNoActiveUserPassword'] . ' ' . Yii::$app->params['adminEmail']);
                }
            } else {

                Yii::$app->session->setFlash('error', Yii::$app->params['settings']['errorNotUserPassword'] . ' ' . Yii::$app->params['adminEmail']);
            }

        }

        return $this->render('forgotpassword', [
            'model' => $model,
        ]);
    }

    // настройка для таблиц

    public function actionSettings($model)
    {
        $this->layout = false;

        $model = \Yii::$app->request->get('model');
        $result = false;
        if(Yii::$app->request->post()){

            // Добаляем пользователю сериалайз массив
            $UserSettings[$model] = Yii::$app->request->post('settingsForm');
            $UserSettings = serialize($UserSettings);

            $user = User::findOne(['id' => Yii::$app->user->identity->id]);
            $user->settings = $UserSettings;
            $user->save();
            $result = true;
        }
        // Если в настройках у пользователя нет данных
        /*
         * Пример массива
         * array(
            'modelName1' => array('0' => 'colomnName1','1' => 'colomnName2'),
            'modelName2' => array('0' => 'colomnName2','1' => 'colomnName1')
        )
         * */

        $UserSettings = unserialize(Yii::$app->user->identity->settings);

        if (empty($UserSettings)) {
            $UserModelSettings = null;
        } else {
            if(!array_key_exists($model, $UserSettings)){
                $UserModelSettings = null;
            } else {
                $UserModelSettings = $UserSettings[$model];
            }
        }

        // Получаем колонки модели
        switch ($model){
            case 'students':
                $attributeLabels = Students::attributeLabels();
                break;
        }

        if (empty($UserModelSettings)) {
           foreach ($attributeLabels as $index => $Label){
               $UserModelSettings[] = $index;
           }
        }

        // Добавляем если добавились новые колонки для пользователя
        // Рендерим форму для выбора для пользователя





        return $this->renderAjax('settings', compact('UserModelSettings', 'attributeLabels', 'result'));
    }
}

controllers/StudentsController.php
<?php

namespace app\controllers;

use app\models\DepartmentList;
use app\models\MaketList;
use app\models\SpecialtyList;
use app\models\UniversityList;
use Yii;
use app\models\Students;
use app\models\StudentsSearch;
use yii\helpers\FileHelper;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\Controller;
use app\models\User;
use \yii\db\Query;
use yii\web\UploadedFile;
use app\models\ExportPdf;
use ZipArchive;


/**
 * StudentsController implements the CRUD actions for Students model.
 */
class StudentsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['login', 'logout', 'index', 'create', 'view', 'update', 'preview', 'print'],
                'rules' => [
                    [
                        'actions' => ['logout', 'index', 'create', 'view', 'update', 'preview', 'print'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Finds the Students model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Students the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Students::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    private function createZip($files)
    {
        $fileArhName = '/uploads/tmp/' . 'maket_archive_' . time() . '.zip';

        $zip = new \ZipArchive();

        if ($zip->open(Yii::getAlias('@webroot') . $fileArhName, ZipArchive::CREATE) !== TRUE) {
            throw new \Exception('Cannot create a zip file');
        }

        foreach ($files as $file) {
            $filename = explode('/', $file);
            $zip->addFile($file, end($filename));
        }

        $zip->close();
        return $fileArhName;
    }

    /**
     * Lists all Students models.
     * @return mixed
     */
    public function actionIndex()
    {
        // Форма смена университета для пользователя
        if (Yii::$app->request->isPost) {
            $dataPost = Yii::$app->request->post();
            if ($dataPost['StudentsSearch']['university_id'] != '' && $dataPost['change_university_id'] == 'Y') {
                $user = User::findOne(Yii::$app->user->identity->id);
                $user->university_id = $dataPost['StudentsSearch']['university_id'];
                $user->save();
                return $this->redirect('index');
            }
        }


        $searchModel = new StudentsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Students model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {

        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionWebcam()
    {
        if (Yii::$app->request->isPost) {


            $uploaddir = Yii::$app->basePath . '/web';
            $uploadname = '/uploads/tmp/' . basename($_FILES['webpict']['name']);
            $uploadfile = $uploaddir . $uploadname;

            if (move_uploaded_file($_FILES['webpict']['tmp_name'], $uploadfile)) {
                return $uploadname;
            } else {
                return "error";
            }

        }
    }

    /**
     * Creates a new Students model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        $model = new Students();

        if (Yii::$app->request->isPost) {


            $dataPost = Yii::$app->request->post();

            // Проверяем есть ли картинка с веб камеры
            if (isset($dataPost['Students']['webcam']) && $dataPost['Students']['webcam'] != '') {

                $filename = str_replace('/uploads/tmp/', "", $dataPost['Students']['webcam']);
                if (!is_dir('uploads/university/' . $dataPost['Students']['university_id'] . '/')) {
                    mkdir('uploads/university/' . $dataPost['Students']['university_id'] . '/', 0755);
                }
                rename(Yii::getAlias('@webroot') . $dataPost['Students']['webcam'], Yii::getAlias('@webroot') . '/uploads/university/' . $dataPost['Students']['university_id'] . '/' . $filename);
                $webcamPath = 'uploads/university/' . $dataPost['Students']['university_id'] . '/' . $filename;


                $model->load(Yii::$app->request->post());
                $model->foto = $webcamPath;
                if ($model->save()) {


                    // Генерируем макет
                    $this->actionPrint($model->id);

                    return $this->redirect(['view', 'id' => $model->id]);
                }
            }


            $model->foto = UploadedFile::getInstance($model, 'foto');

            if ($model->upload()) {
                $path = $model->foto;

                $model->load(Yii::$app->request->post());
                $model->foto = $path;

                if ($model->save()) {


                    // Генерируем макет
                    $this->actionPrint($model->id);

                    return $this->redirect(['view', 'id' => $model->id]);
                }
            }

        }


        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionPreview()
    {
        $this->layout = false;
        $modelPost = Yii::$app->request->post();
        $model = $modelPost['data'];

        return $this->renderAjax('preview', compact('model'));

        /*        return $this->render('preview', [
                    'model' => $model,
                ]);*/
    }

    /**
     * Updates an existing Students model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if (Yii::$app->request->isPost) {

            $arrfoto = UploadedFile::getInstance($model, 'foto');

            if (!empty($arrfoto)) {
                $model->foto = $arrfoto;
                if ($model->upload()) {
                    $path = $model->foto;

                    $model->load(Yii::$app->request->post());
                    $model->foto = $path;

                    if ($model->save()) {

                        // Генерируем макет
                        $this->actionPrint($model->id);

                        return $this->redirect(['view', 'id' => $model->id]);
                    }
                }
            } else {
                $model->load(Yii::$app->request->post());

                if ($model->save()) {

                    // Генерируем макет
                    $this->actionPrint($model->id);
                    return $this->redirect(['view', 'id' => $model->id]);
                }
            }


        }

        /*        if ($model->load(Yii::$app->request->post()) && $model->save()) {
                    return $this->redirect(['view', 'id' => $model->id]);
                }*/

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Students model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);

        // Сначала удаляем Макет
        if ($model->maket_id != '') {
            $maket = MaketList::findOne($model->maket_id);
            FileHelper::unlink(Yii::getAlias('@webroot/') . $maket->path);
        }

        if ($model->foto != '') {
            // Потому удаляем картинку
            FileHelper::unlink(Yii::getAlias('@webroot/') . $model->foto);
        }

        $model->delete();

        return $this->redirect(['index']);
    }

    public function actionDeleteAll()
    {

        if (Yii::$app->request->post()) {
            $postData = Yii::$app->request->post();
            foreach ($postData['data'] as $idItem) {
                $this->actionDelete($idItem);
            }
            Yii::$app->session->setFlash('success', 'Записи удалены.');

            return $this->redirect(['index']);
        }

    }

    public function actionDownloadAll()
    {
        //$start = microtime(true);

        if (Yii::$app->request->post()) {
            $postData = Yii::$app->request->post();


            $allPath = array();

            foreach ($postData['data'] as $idItem) {
                $model = Students::findOne($idItem);
                // Проверяем создал ли макет
                if ($model->maket_id == null) {
                    $filePath = $this->actionPrint($idItem)->path;
                } else {
                    $filePath = MaketList::findOne($model->maket_id)->path;
                }
                $allPath[] = Yii::getAlias('@webroot/') . $filePath;
                if($model->print == 0){

views/students/_maketcard.php
<?php

use yii\helpers\Html;
use \app\models\Students;
use \app\models\UniversityList;
use \app\models\DepartmentList;

/* @var $this yii\web\View */
/* @var $model app\models\Students */
/* @var $form yii\widgets\ActiveForm */
$arResult = array(
    'Students[university_id]' => 1,
    'Students[university_name]' => '',
    'Students[surname]' => '',
    'Students[name]' => '',
    'Students[middle_name]' => '',
    'Students[department_name_ru]' => '',
    'Students[department_name_en]' => '',
    'Students[validity]' => '1',
    'Students[date_birth]' => '',
    'Students[form_training]' => 0,
    'Students[foto]' => '/i/photo.jpg',
);


foreach ($model as $item) {
    if ($item['value'] != '') {
        $arResult[$item['name']] = $item['value'];
    }
}
// Получаем название Вуза
if (isset($arResult['Students[university_id]'])) {
    $Vus = UniversityList::find()->where(['id' => $arResult['Students[university_id]']])->asArray()->one();
    if ($Vus['name'] != '') {
        $arResult['Students[university_name]'] = $Vus['name'];
    } elseif ($Vus['full_name']) {
        $arResult['Students[university_name]'] = $Vus['full_name'];
    }
}

if (isset($arResult['Students[department_id]'])) {
    $dem = DepartmentList::find()->where(['id' => $arResult['Students[department_id]']])->asArray()->one();

    if ($dem['name_ru'] != '') {
        $arResult['Students[department_name_ru]'] = $dem['name_ru'];
    }
    if ($dem['name_en']) {
        $arResult['Students[department_name_en]'] = $dem['name_en'];
    }
}
if(isset($arResult['Students[validity]'])){
    if($arResult['Students[validity]'] > 5){
        $arResult['Students[validity]'] = 5;
    }
}
?>
<div class="card">
    <div class="card__top">
        <div class="card__photo">
            <img src="/i/photo.jpg" alt="">
        </div>
        <div class="card__info">
            <div class="card__info-top">
                <div class="card__stek-logo">
                    <img src="/i/stek-logo-color.svg" alt="">
                </div>
                <div class="card__tu-logo">
                    <img src="/i/tu-logo.svg" alt="">
                </div>
                <div class="card__barcode">
                    <img src="/i/barcode.png" alt="">
                </div>
            </div>
            <div class="card__info-header">
                <strong>Студенческая электронная карта</strong><br>
                Student identity card | <a href="http://stec.me">http://stec.me</a>
            </div>
            <div class="card__name-ru">
                <? if ($arResult['Students[form_training]'] == 0){?>
                <?= $arResult['Students[surname]'] ?><br>
                <?= $arResult['Students[name]'] ?> <?= $arResult['Students[middle_name]'] ?>
                <? } else {?>
                <b><?= $arResult['Students[surname]'] ?></b><br>
                <b><?= $arResult['Students[name]'] ?></b> <b><?= $arResult['Students[middle_name]'] ?></b>
                <?}?>
            </div>
            <div class="card__name-en">
                <?= Students::transliteration($arResult['Students[surname]'], false) ?> <?= Students::transliteration($arResult['Students[name]'], false) ?>
            </div>
            <div class="card__props">
                Дата рождения: <span><?= $arResult['Students[date_birth]'] ?></span>
            </div>
            <div class="card__props">
                Факультет: <span><?= $arResult['Students[department_name_ru]'] ?></span>
            </div>
            <div class="card__props">
                Department: <span><?= $arResult['Students[department_name_en]'] ?></span>
            </div>
        </div>
    </div>
    <div class="card__bottom">
        <span class="card__flags">
            <div class="card__flag card__flag_ru">
                <img src="/i/flag-ru.png" alt="">
            </div>
            <div class="card__flag card__flag_eu">
                <img src="/i/flag-eu.png" alt="">
            </div>
            <div class="card__flags-note">valid in EU</div>
        </span>
        <span class="card__valid">
            <span>действительна до 31 октября</span>
        </span>
        <span class="card__years">
            <? for ($colomn = 0; $colomn < $arResult['Students[validity]']; $colomn++) { ?>
                <div class="card__year">
                    <span><?= date('Y', strtotime('+' . $colomn . ' year')) ?></span>
                    <img src="/i/stek-logo-bw.svg" alt="">
                </div>
            <? } ?>
        </span>
    </div>
    <div class="card__univercity-name">
        <svg id="svgRoot" class="content" preserveAspectRatio="xMidYMid meet" viewBox="0 0 50 20">
            <text id="text" x="0" y="0" font-size="14" dy="0" fill="#fff" font-family="MyriadPro, sans-serif">
                <tspan x="0" y="14"><?= $arResult['Students[university_name]'] ?></tspan>
            </text>
        </svg>
    </div>
</div>

views/students/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Students */

$this->title = 'Создание студента';
$this->params['breadcrumbs'][] = ['label' => 'Список студентов', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-list-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/students/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\models\Students;
use kartik\daterange\DateRangePicker;
use yii\helpers\Url;
use app\models\User;

/* @var $this yii\web\View */
/* @var $searchModel app\models\StudentsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Список студентов';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="user-list-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php
    if (Yii::$app->user->identity->role == User::ROLE_SUPERADMIN) {
        echo $this->render('_search', ['model' => $searchModel]);
    }
 ?>


    <div>
        <?= Html::a('Добавить студента', ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Скачать макет ', ['download'], ['class' => 'btn btn-primary ajax-maket-download']) ?>
        <?= Html::a('Удалить ', '#', ['class' => 'btn btn-danger ajax-all-delete']) ?>
        <?= Html::a('Очистить Фильтр    ', ['index'], ['class' => 'btn btn-primary']) ?>
        <a data-pjax="0" data-toggle='modal' data-target='#Settings'
           href="<?= Url::to(['site/settings', 'model' => 'students']); ?>"
           class="btn btn-info pull-right modalButton">Настройка</a>

        <?
        // Количество записей
        $values = Yii::$app->params['pagelist'];
        $current = $dataProvider->getPagination()->getPageSize();
        ?>
        <div class="dataTables_length pull-right" id="datatable_length"><label>Показывать по
                <select class="form-control" onchange="location = this.value;">
                    <?php foreach ($values as $value): ?>
                        <option value="<?= Html::encode(Url::current(['per-page' => $value, 'page' => null])) ?>"
                                <?php if ($current == $value): ?>selected="selected"<?php endif; ?>><?= $value ?></option>
                    <?php endforeach; ?>
                </select> записи </label></div>

    </div>


    <?

    //$colomnTable[] = array('class' => 'yii\grid\SerialColumn');
    $colomnTable[] = array('class' => 'yii\grid\CheckboxColumn');
    // Получаем из настроек
    $UserSettings = unserialize(Yii::$app->user->identity->settings);
    $attributeLabels = Students::attributeLabels();

    if (empty($UserSettings) && empty($UserSettings['students'])) {


        foreach ($attributeLabels as $index => $Label) {
            $UserSettings['students'][] = $index;
        }
    }


    foreach ($UserSettings['students'] as $label) {

        if (array_key_exists($label, $attributeLabels)) {
            switch ($label) {
                case 'university_id':
                case 'department_id':
                case 'specialty_id':
                    continue;
                    break;
                case 'date_update':
                case 'date_add':
                    $colomnTable[] = ['attribute' => $label, 'format'=> 'datetime', 'value' => $label, 'filter' =>
                        DateRangePicker::widget([
                            'model' => $searchModel,
                            'attribute' => $label,
                            //'convertFormat' => true,
                            'options' => ['placeholder' => 'Выберите дату ...', 'class' => 'form-control'],
                            'language' => 'ru',
                            'pluginOptions' => [
                                'timePicker' => false,
                                'timePickerIncrement' => 30,
                                'locale' => [
                                    'format' => 'D.MM.Y'
                                ]
                            ]
                        ])];
                    break;
                case 'print':
                    $colomnTable[] = [
                        'attribute' => $label, 'value' => 'printStatus', 'filter' => Students::getPrintStatusList(),
                    ];
                    break;
                case 'form_training':
                    $colomnTable[] = [
                        'attribute' => $label, 'value' => 'formtrainingName', 'filter' => Students::getFormTraining(),
                    ];
                    break;
                default:
                    $colomnTable[] = $label;
                    break;
            }
        }
    }

    $colomnTable[] = array(
        'class' => 'yii\grid\ActionColumn',
        'template' => '{download}{view}{update}{delete}',
        'buttons' => [
            'download' => function ($url, $model, $key) {
                return Html::a('<span class="glyphicon glyphicon-download-alt"></span>', ['download', 'id' => $model->id] , [
                    'title' => 'Скачать макет',
                    'class' => '']);
            }

        ],
    );
    ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'layout' => "{items}\n{pager}\n{summary}",

        'columns' => $colomnTable
        /*'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            //'date_add:date',
            ['attribute' => 'date_add', 'format' => 'date', 'value' => 'date_add', 'filter' =>
                DateRangePicker::widget([
                    'model' => $searchModel,
                    'attribute' => 'date_add',
                    //'convertFormat' => true,
                    'options' => ['placeholder' => 'Выберите дату ...', 'class' => 'form-control'],
                    'language' => 'ru',
                    'pluginOptions' => [
                        'timePicker' => false,
                        'timePickerIncrement' => 30,
                        'locale' => [
                            'format' => 'D.MM.Y'
                        ]
                    ]
                ])],
            'date_update:date',
            'surname',
            'name',
            'middle_name',
            'university.name',
            'department.name_ru',
            'specialty_id',

            //'course',
            //'validity',
            //'date_birth',
            //'phone',
            //'form_training',
            //'print',
            //'card_id',
            //'comment:ntext',
            //'foto',
            //'maket_id',

            ['class' => 'yii\grid\ActionColumn'],
        ],*/
    ]); ?>
</div>
<?
$this->registerJs("
jQuery(document).on('submit', '#settingsform', function (e){
        e.preventDefault();
         var url = location.href;
         var idform = $(this).attr('data-target');
        $.get($(this).attr('data-href'), function(data) {
            location.href = url;
        });
    });
");
$this->registerJs("
    $('.ajax-all-delete').on('click', function(e) {
        e.preventDefault();
        result = confirm('Вы уверены, что хотите удалить выбранные элементы?');
        if(result){
        var data = [];
        $('.grid-view tbody tr').each(function(){
            if($(this).find('input[name=\"selection[]\"]').prop('checked')){
                data[data.length] = $(this).attr('data-key')
            }
        });
        console.log(data);
        $.ajax({
            url: '/students/delete-all',
            type:'POST',
            data:{data: data},

        });
        }
    });
    $('.ajax-maket-download').on('click', function(e) {
        e.preventDefault();
        result = confirm('Вы уверены, что хотите сформировать макеты для выбранные элементов?');
        if(result){
        var data = [];
        $('.grid-view tbody tr').each(function(){
            if($(this).find('input[name=\"selection[]\"]').prop('checked')){
                data[data.length] = $(this).attr('data-key')
            }
        });
        console.log(data);
        $.ajax({
            url: '/students/download-all',
            type:'POST',
            data:{data: data},
            success: function(res){
             console.log(res);
            }
        });
        }
    });
");

?>
<script>

</script>

views/students/preview.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Students */

?>
    <?= $this->render('_maketcard', [
        'model' => $model,
    ]) ?>

views/students/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Students */

$this->title = 'Изменить: ' . $model->name . ' ' . $model->surname;
$this->params['breadcrumbs'][] = ['label' => 'Список студентов', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Изменить';
?>
<div class="user-list-update">

    <h1><?= Html::encode($this->title) ?></h1>
    <p>
        <?= Html::a('Закрыть', ['index'], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы уверены, что хотите удалить этот элемент?',
                'method' => 'post',
            ],
        ]) ?>
    </p>
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>